/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.PGMImage to edit this template
 */
package edu.centralenantes.tp2test;

/**
 *
 * @author dodi
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Simple grayscale image stored as PGM (P2 ASCII), max value 255.
 */
public class PGMImage {

    private final int width;
    private final int height;
    private final int[][] pixels; // pixels[y][x], values 0..255

    /**
     * Creates an empty image filled with 0.
     * @param width image width (columns)
     * @param height image height (rows)
     */
    public PGMImage(int width, int height) {
        if (width <= 0 || height <= 0) throw new IllegalArgumentException("Invalid size");
        this.width = width;
        this.height = height;
        this.pixels = new int[height][width];
    }

    public int getWidth() { return width; }
    public int getHeight() { return height; }

    public int get(int x, int y) { return pixels[y][x]; }

    public void set(int x, int y, int value) {
        if (value < 0) value = 0;
        if (value > 255) value = 255;
        pixels[y][x] = value;
    }

    /**
     * Reads a PGM ASCII (P2) file.
     * Supports comments (# ...) and arbitrary whitespace.
     * @param path file path
     * @return loaded image
     * @throws IOException if read fails or format is invalid
     */
    public static PGMImage read(Path path) throws IOException {
        List<String> tokens = new ArrayList<>();

        try (BufferedReader br = Files.newBufferedReader(path)) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;
                if (line.startsWith("#")) continue;

                // Remove inline comments: "12 34 # comment"
                int idx = line.indexOf('#');
                if (idx >= 0) line = line.substring(0, idx).trim();
                if (line.isEmpty()) continue;

                String[] parts = line.split("\\s+");
                for (String p : parts) {
                    if (!p.isEmpty()) tokens.add(p);
                }
            }
        }

        if (tokens.size() < 4) throw new IOException("Invalid PGM: not enough tokens");

        int i = 0;
        String magic = tokens.get(i++);
        if (!"P2".equals(magic)) throw new IOException("Invalid PGM: expected P2, got " + magic);

        int width = Integer.parseInt(tokens.get(i++));
        int height = Integer.parseInt(tokens.get(i++));
        int maxVal = Integer.parseInt(tokens.get(i++));
        if (maxVal != 255) throw new IOException("Invalid PGM: expected max 255, got " + maxVal);

        PGMImage img = new PGMImage(width, height);

        int expected = width * height;
        if (tokens.size() - i < expected) {
            throw new IOException("Invalid PGM: not enough pixel values");
        }

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                int v = Integer.parseInt(tokens.get(i++));
                img.set(x, y, v);
            }
        }
        return img;
    }

    /**
     * Writes image as PGM ASCII (P2). Enforces max line length ~ 70 chars.
     * @param path output file path
     * @throws IOException if write fails
     */
    public void write(Path path) throws IOException {
        try (BufferedWriter bw = Files.newBufferedWriter(path)) {
            bw.write("P2\n");
            bw.write("# generated by PGMImage\n");
            bw.write(width + " " + height + "\n");
            bw.write("255\n");

            int lineLen = 0;
            for (int y = 0; y < height; y++) {
                for (int x = 0; x < width; x++) {
                    String s = Integer.toString(pixels[y][x]);
                    // +1 for space if needed
                    int add = (lineLen == 0 ? s.length() : 1 + s.length());
                    if (lineLen + add > 70) {
                        bw.write("\n");
                        lineLen = 0;
                    }
                    if (lineLen != 0) {
                        bw.write(' ');
                        lineLen += 1;
                    }
                    bw.write(s);
                    lineLen += s.length();
                }
                bw.write("\n");
                lineLen = 0;
            }
        }
    }
}
